spring:
    profiles:
        active: prod
    devtools:
        restart:
            enabled: false

    thymeleaf:
        cache: true

    #jade4j:
    #    caching: true

    jpa:
        show-sql: true

    datasource:
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        initialize: true

        #hikari:
        jpa:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true

    redis:
      host: redis
      port: 6379
      default_expire_time: 86400

logging:
  level:
    org.springframework.web: ERROR
    com.raysmond.blog: DEBUG